language: c
sudo: true
dist: xenial

env:
  global:
    - NAME: tesseract
    - ASDF_SYSTEM: bodge-tesseract-v3
    - PATH: ~/bin/:$PATH
    - secure: "DI2X360FtvKnr5txcLZ+BR1Ky4DEzn7s8DN3Jz7qJ3929eWJjNbPt9b3Y7k+rBevm0aB00jSZvDkH1I29LVUlacBD4xSa+tgFj1jy01kPnHMYe1WJL/8MrzZIb7d6+Z/yzEMivRzJ4lraz+2xGEM8C2WsaJoslwiZYXRBhPn0u9fZ1XJzMb3hztHhiawS5RLDNI+oR4CzkMNzjKXi3ljBoMNmRfuSvA6XfYT4H8Jw2vpBsFJb9rbT1HQQQaCCkzXPuLcDeJWeDjsjvVG4Dm9zxpPL0knw1r7kgpO/kOergEY7JbBmDRLcntZ/kuOoC2F9AkO7dAl1yTbulsylH5wNDcon313w8h50OhfvLJW8UxxKVLHbl8RRZZAyYdomfb3fHztb0pvbesAgb59J8FBWguad+1kO4D2jBKPw6ldRavrIlQQRUzaECr0ts8o6H19ERSkIUcfk4hxqZZaimi5QkYdO58TXDJLKAB4JQgljppG8NMLKxcJDxUr1Dj9wd1zuNM3oDkNb9Z1i5nCUySyIwnZ1D20XXDcO66ZGLbW6wyN/sYAVv6TdbuVXOOqlgs9538wJ5rJfzmGsLksNeT7rPI4BAi52sjOZwOnakB/84RWcFWX3aw6x7cjhcV7uopI6uvZ1BoBkZBvkyxGuGpo/SLYuLqNPsVAt235Uixyxsc="

matrix:
  include:
  - os: linux
    env:
      - TARGET_ARCH=i686
      - CFLAGS=-m32
      - EXTENSION=so
  - os: linux
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=so
  - os: osx
    env:
      - TARGET_ARCH=i686
      - CFLAGS=-m32
      - EXTENSION=dylib
  - os: osx
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=dylib

branches:
  only:
  - "/^v\\d+(\\.\\d+)+$/"

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:alex-p/tesseract-ocr -y;
      sudo apt-get update -q;
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends install patchelf g++ g++-multilib libc6-dev-i386 libtool-bin autoconf automake libleptonica-dev;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update && brew install libtool leptonica;
    fi

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - ln -s $TRAVIS_BUILD_DIR/ ~/quicklisp/local-projects/$ASDF_SYSTEM

script:
  - cd $TRAVIS_BUILD_DIR/lib/ && make clean build
  - rm -rf $TRAVIS_BUILD_DIR/spec/*
  - lisp "$TRAVIS_BUILD_DIR/util/regen-spec.lisp" "$ASDF_SYSTEM" t $TARGET_ARCH
  - cd $TRAVIS_BUILD_DIR/ && zip -r spec.zip spec/

before_deploy:
  - export TARGET_FILE=$TRAVIS_BUILD_DIR/lib$NAME.$EXTENSION.bodged-$TARGET_ARCH-$TRAVIS_OS_NAME-$TRAVIS_BRANCH
  - export SPEC_ARCHIVE=$TARGET_FILE-spec.zip
  - mv $TRAVIS_BUILD_DIR/lib/lib$NAME.$EXTENSION.bodged $TARGET_FILE
  - mv $TRAVIS_BUILD_DIR/spec.zip $SPEC_ARCHIVE

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: [$TARGET_FILE, $SPEC_ARCHIVE]
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
